# Generated by Django 4.2.28 on 2026-02-19 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='especialidad',
            field=models.CharField(choices=[('NEUMOLOGIA_ADULTO', 'Neumología Adulto'), ('NEUMOLOGIA_PEDIATRICA', 'Neumología Pediátrica'), ('ALERGOLOGIA', 'Alergología'), ('MEDICINA_GENERAL', 'Medicina General')], max_length=100),
        ),
    ]
