# Generated by Django 4.2.28 on 2026-02-19 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0002_alter_medico_especialidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='especialidad',
            field=models.CharField(choices=[('Neumología Adulto', 'Neumología Adulto'), ('Neumología Pediátrica', 'Neumología Pediátrica'), ('Alergología', 'Alergología'), ('Medicina General', 'Medicina General')], max_length=100),
        ),
    ]
