# Generated by Django 4.2.28 on 2026-02-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarifas', '0003_rename_servicio_tarifa_alter_tarifa_options'),
        ('medicos', '0003_alter_medico_especialidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='servicios',
            field=models.ManyToManyField(blank=True, related_name='medicos', to='tarifas.tarifa'),
        ),
    ]
