# Generated by Django 4.2.28 on 2026-02-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0005_medico_registrado_por_alter_medico_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default='2026-01-01'),
            preserve_default=False,
        ),
    ]
