# Generated by Django 4.2.28 on 2026-02-20 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tarifas', '0006_alter_tarifa_fecha_registro'),
        ('medicos', '0006_alter_medico_fecha_registro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('fecha_labor', models.DateField(verbose_name='Fecha de Realización')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Sistema')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producciones', to='medicos.medico', verbose_name='Médico')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Persona Responsable')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producciones_servicio', to='tarifas.tarifa', verbose_name='Servicio Realizado')),
            ],
            options={
                'verbose_name': 'Registro de Producción',
                'verbose_name_plural': 'Registros de Producción',
                'ordering': ['-fecha_labor', '-fecha_registro'],
            },
        ),
    ]
