# Generated by Django 4.2.28 on 2026-02-20 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0007_produccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='produccion',
            name='precio_aplicado',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10, verbose_name='Precio Aplicado'),
            preserve_default=False,
        ),
    ]
