# Generated by Django 4.2.28 on 2026-03-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0008_produccion_precio_aplicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='sede',
            field=models.CharField(choices=[('Principal', 'Principal'), ('Cabecera', 'Cabecera'), ('Machado', 'Machado'), ('Prado', 'Prado'), ('FOSUNAB 6', 'Fosunab 6'), ('FOSUNAB 7', 'Fosunab 7'), ('FOSUNAB 8', 'FOSUNAB 8')], default='Sin sede', max_length=100),
        ),
    ]
