# Generated by Django 4.2.28 on 2026-03-12 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0009_medico_sede'),
    ]

    operations = [
        migrations.AddField(
            model_name='produccion',
            name='sede_momento',
            field=models.CharField(default='sin sede', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produccion',
            name='unidad_negocio_momento',
            field=models.CharField(default='sin unidad negocio', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medico',
            name='sede',
            field=models.CharField(choices=[('Principal', 'Principal'), ('Cabecera', 'Cabecera'), ('Machado', 'Machado'), ('Prado', 'Prado'), ('Fosunab 6', 'Fosunab 6'), ('Fosunab 7', 'Fosunab 7'), ('Fosunab 8', 'Fosunab 8')], default='Sin sede', max_length=100),
        ),
    ]
