# Generated by Django 4.2.28 on 2026-03-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0010_produccion_sede_momento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='especialidad',
            field=models.CharField(choices=[('Neumología Adulto', 'Neumología Adulto'), ('Neumología Pediátrica', 'Neumología Pediátrica'), ('Alergología', 'Alergología'), ('Cardiología', 'Cardiología'), ('Internista', 'Internista'), ('Juntas Médicas', 'Juntas Médicas')], max_length=100),
        ),
    ]
