# Generated by Django 4.2.28 on 2026-03-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0011_alter_medico_especialidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='produccion',
            name='subunidad_momento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sub-Unidad al momento'),
        ),
    ]
