# Generated by Django 4.2.28 on 2026-02-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarifas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='unidad_negocio',
            field=models.CharField(choices=[('SERVICIO MEDICO', 'Servicio Médico'), ('INTERCONSULTA', 'Interconsulta'), ('LAB. PULMONAR', 'Laboratorio Pulmonar'), ('CLINICA DE ALERGIAS', 'Clínica de Alergias'), ('CLINICA DE SUEÑO', 'Clínica de Sueño'), ('PROCEDIMIENTOS', 'Procedimientos'), ('PROGRAMAS INTEGRALES', 'Programas Integrales'), ('INVESTIGACIÓN', 'Investigación')], default='', max_length=50, verbose_name='Unidad de Negocio'),
            preserve_default=False,
        ),
    ]
