# Generated by Django 4.2.28 on 2026-02-20 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarifas', '0002_servicio_unidad_negocio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servicio',
            new_name='Tarifa',
        ),
        migrations.AlterModelOptions(
            name='tarifa',
            options={'verbose_name': 'Tarifa', 'verbose_name_plural': 'Tarifas'},
        ),
    ]
