# Generated by Django 4.2.28 on 2026-02-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarifas', '0003_rename_servicio_tarifa_alter_tarifa_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifa',
            name='precio',
            field=models.PositiveIntegerField(verbose_name='Precio del Servicio'),
        ),
    ]
