# Generated by Django 4.2.28 on 2026-03-25 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarifas', '0006_alter_tarifa_fecha_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifa',
            name='subunidad_procedimientos',
            field=models.CharField(choices=[('PROCEDIMIENTOS DIAGNOSTICOS', 'Procedimientos Diagnósticos'), ('PROCEDIMIENTOS DE INTERVENCIONISMO', 'Procedimientos de Intervencionismo')], default='', max_length=100),
            preserve_default=False,
        ),
    ]
