# Generated by Django 4.2.28 on 2026-03-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarifas', '0008_alter_tarifa_subunidad_procedimientos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifa',
            name='subunidad_procedimientos',
            field=models.CharField(blank=True, choices=[('DIAGNOSTICOS', 'Diagnósticos'), ('INTERVENCIONISMO', 'Intervencionismo')], max_length=100, null=True, verbose_name='Sub-Unidad Procedimientos'),
        ),
    ]
